---
- name: Where this playbook is running
  ansible.builtin.debug:
    msg: 'Running as "{{ ansible_user_id }}" in server: "{{ ansible_hostname }}"'

- name: Create RHELUpgradeChecks directory in user's home
  file:
    path: "/home/{{ ansible_user_id }}/RHELUpgradeChecks"
    state: directory
    mode: '0755'

- name: Run crontab -l and save output
  ansible.builtin.shell: crontab -l
  async: 5
  poll: 5
  register: cron_result
  ignore_errors: true

- name: Run sudo -l and save output
  ansible.builtin.shell: sudo -l
  async: 5
  poll: 5
  register: sudo_result
  ignore_errors: true

- name: Run chage -l for root and save output
  ansible.builtin.shell: chage -l
  async: 5
  poll: 5
  register: chage_result
  ignore_errors: true

- name: Save crontab output to file on remote host
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_crontab.txt"
    content: "{{ (cron_result.stdout + cron_result.stderr) | default('No crontab for this user') }}"

- name: Save sudo -l output to file on remote host
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_sudo.txt"
    content: "{{ (sudo_result.stdout + sudo_result.stderr) | default('') }}"

- name: Save chage -l output to file on remote host
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_chage.txt"
    content: "{{ (chage_result.stdout + chage_result.stderr) | default('') }}"

- name: Ensure to backup of .bashrc file
  ansible.builtin.copy:
    src: "/home/{{ ansible_user_id }}/.bashrc"
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_bashrc.txt"
    remote_src: true

- name: Ensure to backup of known_host file
  ansible.builtin.copy:
    src: "/home/{{ ansible_user_id }}/.ssh/known_hosts"
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_known_hosts.txt"
    remote_src: true

- name: Ensure to backup of authorized_keys file
  ansible.builtin.copy:
    src: "/home/{{ ansible_user_id }}/.ssh/authorized_keys"
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_authorized_keys.txt"
    remote_src: true

- name: Ensure to backup of fstab file
  ansible.builtin.copy:
    src: /etc/fstab
    dest: "/home/{{ ansible_user_id }}/RHELUpgradeChecks/{{ prefix }}_{{ ansible_hostname }}_fstab.txt"
    remote_src: true
